### ISSUE TITLE
Local path disclosure

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1059]
As reported by `sp1d3rs` in https://hackerone.com/bugs?subject=tts-private&report_id=246071:

> Hi. I found a local path disclosure through error message on the different endpoints. For example, upon submiting the site settings to the endpoint http://<host>/v0/site/<siteid> this JSON request is sent:
> 
> ```json
> {
>     "enableSave": true,
>     "demoBranch": "",
>     "demoDomain": "",
>     "config": "",
>     "previewConfig": "",
>     "demoConfig": "",
>     "defaultBranch": "master",
>     "domain": "",
>     "engine": "jekyll"
> }
> ```
>
> However, if we change the enableSave option to the `falses` using web debugger, we will get next error message:
> 
> 
> <pre>SyntaxError: Unexpected token s in JSON at position 19<br> &nbsp; &nbsp;at Object.parse (native)
> <br> &nbsp; &nbsp;at parse (/home/test/federalist/node_modules/body-parser/lib/types/json.js:88:17)
> <br> &nbsp; &nbsp;at /home/test/federalist/node_modules/body-parser/lib/read.js:116:18<br> &nbsp;
>  &nbsp;at invokeCallback (/home/test/federalist/node_modules/raw-body/index.js:262:16)<br> &nbsp; 
> &nbsp;at done (/home/test/federalist/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at 
> IncomingMessage.onEnd (/home/test/federalist/node_modules/raw-body/index.js:307:7)<br> &nbsp; 
> &nbsp;at emitNone (events.js:86:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)<br> 
> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:974:12)<br> &nbsp; &nbsp;at 
> _combinedTickCallback (internal/process/next_tick.js:80:11)<br> &nbsp; &nbsp;at 
> process._tickDomainCallback (internal/process/next_tick.js:128:9)</pre>
> As you see, it disclosed full path to the installed app on my localhost - /home/test/federalist/. It is minor information leak, which should to be fixed.
> 
> Same issue exists on other endpoints like http://<host>/v0/build/, http://<host>/v0/site (owner and engine fields) - in case wrong JSON will be submitted, trace with local path disclosure will be thrown.

**Comment by jseppi** [comment]
Actually, this is invalid. We do not get local path disclosure from this method in staging or production, only in development.

This is because on staging/prod, we have `NODE_ENV='production'`, which Express uses in its default error handling middleware to not show stack traces: http://expressjs.com/en/guide/error-handling.html#the-default-error-handler
