### ISSUE TITLE
Trying to load specific logs on Federalist crashes the app  (logs for build failing on package.json)

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1791]
#### User Story
A user with a large log (5MB) can view/download the logs without crashing Federalist web engine.

#### Acceptance Criteria

- [x] build log api take pages as params and returns result set accordingly
- [x] buildlog iterates through pages and displays logs
- [ ] download - download logs using pagination

#### Level of effort - <low/medium/high>
Medium

**Comment by wslack** [comment]
suborned #1808

**Comment by wslack** [comment]
@amirbey to edit as well.

**Comment by wslack** [comment]
(also taking care of https://github.com/18F/federalist/issues/1183 a bit)

**Comment by amirbey** [comment]
https://github.com/joshbruce/sam-design-system-site/commit/46461c5b5aa1ac991172b7b6557610d15cdbb6c0

#### Description of feature or bug

2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR Unable to save binary /usr/local/nvm/versions/node/v8.11.1/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/usr/local/nvm/versions/node/v8.11.1/lib/node_modules/@angular/cli/node_modules/node-sass/vendor'
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR     at Object.fs.mkdirSync (fs.js:885:18)
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR     at sync (/usr/local/nvm/versions/node/v8.11.1/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:71:13)
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR     at Function.sync (/usr/local/nvm/versions/node/v8.11.1/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:77:24)
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR     at checkAndDownloadBinary (/usr/local/nvm/versions/node/v8.11.1/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:114:11)
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/usr/local/nvm/versions/node/v8.11.1/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:157:1)
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:652:30)
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:663:10)
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR     at Module.load (module.js:565:32)
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:505:12)
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:497:3)
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR   errno: -13,
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR   code: 'EACCES',
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR   syscall: 'mkdir',
   2018-04-23T13:05:43.19-0400 [APP/PROC/WEB/0] ERR   path: '/usr/local/nvm/versions/node/v8.11.1/lib/node_modules/@angular/cli/node_modules/node-sass/vendor' }
 this is fixed by adding .nvrmc

however the logging is not available in Fedealist
