### ISSUE TITLE
Recieving a webhook throws an error

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#20]
I made some changes to a repo, and once my local app received the webhoook request I got the following error:

```
Unhandled rejection Error (E_VALIDATION) :: 1 attribute is invalid
    at WLValidationError.WLError (/Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/lib/waterline/error/WLError.js:26:15)
    at new WLValidationError (/Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/lib/waterline/error/WLValidationError.js:20:28)
    at /Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/lib/waterline/query/validate.js:45:43
    at allValidationsChecked (/Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:198:5)
    at done (/Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:167:19)
    at /Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:40:16
    at /Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:179:23
    at done (/Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:167:19)
    at /Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:40:16
    at /Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:152:64
    at /Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:157:13
    at _each (/Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:156:9)
    at validate (/Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:151:11)
    at /Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:157:13
    at _each (/Users/JeremiaKimelman/Developer/code/18f/federalist/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:57:9)
```

How to reproduce:

0. Register an app that has a github repo
0. Make changes (could be through markdown editor on Github.com) and commit them
0. Check shell were server process is running. You will see the error

**Comment by jeremiak** [comment]
Here's what I think this is after I just had to debug it on my local machine. The `error` attribute on the model is a `string` but the `err` object that gets assigned to it is an object. Seems like we could just change [`string`](https://github.com/18F/federalist/blob/master/api/models/Build.js#L12) to `object` and be good to go?

**Comment by dhcole** [comment]
Thanks for debugging. Sometimes the error will actually be a string... I'll see if I can force it to always be so.
