### ISSUE TITLE
Cannot delete site

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#2546]
#### User Story

Unable to delete a site of which I am an owner
![Screen Shot 2020-04-08 at 9.48.55 AM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/2ba89cee-482d-4603-9c6d-eb6a45afe5ee)

```
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT error: {
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "description": "Service instance o-davemcorwin-r-federalist-uswds-gatsby: Service broker error: BucketNotEmpty: The bucket you tried to delete is not empty",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "error_code": "CF-ServiceBrokerBadResponse",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "code": 10001,
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "http": {
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     "uri": "https://s3-broker.app.cloud.gov/v2/service_instances/4f722ad2-2efc-4365-9802-f4e7bd5c687e",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     "method": "DELETE",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     "status": 500
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   }
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT }
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT Error: {
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "description": "Service instance o-davemcorwin-r-federalist-uswds-gatsby: Service broker error: BucketNotEmpty: The bucket you tried to delete is not empty",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "error_code": "CF-ServiceBrokerBadResponse",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "code": 10001,
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "http": {
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     "uri": "https://s3-broker.app.cloud.gov/v2/service_instances/4f722ad2-2efc-4365-9802-f4e7bd5c687e",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     "method": "DELETE",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     "status": 500
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   }
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT }
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at Request.request [as _callback] (/home/vcap/app/api/utils/cfApiClient.js:196:18)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at Request.self.callback (/home/vcap/deps/0/node_modules/request/request.js:185:22)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at Request.emit (events.js:198:13)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at Request.EventEmitter.emit (domain.js:448:20)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at Request.<anonymous> (/home/vcap/deps/0/node_modules/request/request.js:1161:10)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at Request.emit (events.js:198:13)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at Request.EventEmitter.emit (domain.js:448:20)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at IncomingMessage.<anonymous> (/home/vcap/deps/0/node_modules/request/request.js:1083:12)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at Object.onceWrapper (events.js:286:20)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at IncomingMessage.emit (events.js:203:15)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at IncomingMessage.EventEmitter.emit (domain.js:448:20)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at endReadableNT (_stream_readable.js:1145:12)
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     at process._tickCallback (internal/process/next_tick.js:63:19) {"service":"federalistapp-staging"}
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT error: Sending 500: {
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "description": "Service instance o-davemcorwin-r-federalist-uswds-gatsby: Service broker error: BucketNotEmpty: The bucket you tried to delete is not empty",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "error_code": "CF-ServiceBrokerBadResponse",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "code": 10001,
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   "http": {
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     "uri": "https://s3-broker.app.cloud.gov/v2/service_instances/4f722ad2-2efc-4365-9802-f4e7bd5c687e",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     "method": "DELETE",
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT     "status": 500
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT   }
   2020-04-08T09:48:53.40-0700 [APP/PROC/WEB/0] OUT }
```

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
cc @amirbey

**Comment by davemcorwin** [comment]
This was caused by and will be addressed as part of the robots.txt work.
