### ISSUE TITLE
Installing Federalist locally fails with "getaddrinfo ENOTFOUND db db:5432"

### ISSUE THREAD

**Issue by nk9** [18F/federalist#2636]
I am attempting to follow the main README's instructions to get Federalist installed locally on Mac OS X 10.14.6. I have all the dependencies, and have followed steps 1–4, except for the Authorized OAuth Apps part. I couldn't understand what was being asked for there, so I skipped it in hopes that it would become clear once the app was up and running and I went to sign in the first time.

I am not an 18F dev, so I skipped that section. I ran `docker-compose build` successfully, but `docker-compose run app yarn` fails:

```
⋊> federalist on staging ◦ docker-compose run app yarn                                                                                                                                14:32:56
Starting federalist_db_1 ... done
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ yarn migrate:up
yarn run v1.22.4
$ node migrate.js up || true
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: getaddrinfo ENOTFOUND db db:5432
    at module.exports (/app/node_modules/db-migrate/lib/commands/helper/assert.js:9:14)
    at /app/node_modules/db-migrate/lib/commands/up.js:19:14
    at /app/node_modules/db-migrate/connect.js:17:7
    at /app/node_modules/db-migrate/lib/driver/index.js:95:9
    at /app/node_modules/db-migrate-pg/index.js:710:7
    at Connection.connectingErrorHandler (/app/node_modules/pg/lib/client.js:213:14)
    at Connection.emit (events.js:198:13)
    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:57:10)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Done in 0.95s.
Done in 2.30s.
```

I've tried re-running earlier steps. I've tried turning off Postgres (the local version which was running on my machine separate from the Federalist install). I've tried a computer restart. Unfortunately, I keep getting the same error.

It looks like the problem is that Node can't reach the Postgres server in the Docker container. When I plow ahead and try `docker-compose run app yarn create-dev-data`, it fails with a slightly more verbose stack. This time it's Sequelize complaining that it can't reach 5432, so it seems like the same root cause.

Interestingly, I'm on the `origin/staging` branch, which is kind of unexpected. I haven't done anything with git beyond cloning it from the 18F repo and `cd`ing into the dir as instructed. I wonder if I should have forked the repo first and cloned my own copy?

I'd appreciate a pointer in the right direction.

**Comment by nk9** [comment]
Hi, Amir. Did you close this because I also sought help on the Slack channel? I am still seeing the same error, and I'm not sure how to overcome it. Deleting and re-creating the Docker containers doesn't help.
