### ISSUE TITLE
Clone from template failing with missing gh-pages remote

### ISSUE THREAD

**Issue by adborden** [18F/federalist#308]
- [ ] find locations of templates

Writing integration tests for federalist and ran into this issue. Repro
1. Login as new user
2. Navigate to http://localhost:1337/#new
3. Click "Use This Template" for the Simple microsite template.

Expected:
no errors

Actual:

```
error: Build error:  Error: Command failed: /bin/sh -c rm -rf ./.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages || true && rm -rf ./.tmp/destination/federalist-test/foo-NEMIfHQDCJ/gh-pages || true && mkdir -p ./.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages && git clone -b gh-pages --single-branch https://***@github.com/federalist-test/foo-NEMIfHQDCJ.git ./.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages && git log -1 --pretty=format:'commit: {%n "commit": "%H",%n "author": "%an <%ae>",%n "date": "%ad",%n "message": "%s"%n}' > ./.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages/_config_base.yml && echo "
baseurl: /site/federalist-test/foo-NEMIfHQDCJ
branch: gh-pages
" >> ./.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages/_config_base.yml && bundle exec jekyll build --safe --config ./.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages/_config.yml,./.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages/_config_base.yml --source ./.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages --destination ./.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages/_site && mkdir -p ./.tmp/destination/federalist-test/foo-NEMIfHQDCJ/gh-pages && cp -r ./.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages/_site/* ./.tmp/destination/federalist-test/foo-NEMIfHQDCJ/gh-pages && rm -rf ./.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages
Cloning into './.tmp/source/federalist-test/foo-NEMIfHQDCJ/gh-pages'...
fatal: Remote branch gh-pages not found in upstream origin

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by wslack** [comment]
Need to verify still a bug

**Comment by el-mapache** [comment]
@wslack I believe this can be closed. We don't have a template named 'Simple Microsite', and none of the existing templates uses `gh-pages` as its default branch.

**Comment by wslack** [comment]
yep, we dropped this template way back in the days.
